# Generated by Django 3.2.7 on 2022-06-26 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('ParentGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='products.category')),
            ],
            options={
                'verbose_name': 'Sub Group',
                'verbose_name_plural': 'Sub Groups',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latest', models.BooleanField(default=True)),
                ('Featured', models.BooleanField(default=True)),
                ('Discount', models.BooleanField(default=True)),
                ('Headings', models.ManyToManyField(to='products.Category')),
            ],
            options={
                'verbose_name': 'Header',
            },
        ),
        migrations.CreateModel(
            name='GroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('ParentGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupitems', to='core.subgroup')),
                ('Subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory')),
            ],
            options={
                'verbose_name': 'Group Item',
                'verbose_name_plural': 'Group Items',
            },
        ),
    ]
