# Generated by Django 3.2.7 on 2022-06-26 12:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image1', models.ImageField(blank=True, null=True, upload_to=core.models.carousel_image_handle)),
                ('Image2', models.ImageField(blank=True, null=True, upload_to=core.models.carousel_image_handle)),
                ('Image3', models.ImageField(blank=True, null=True, upload_to=core.models.carousel_image_handle)),
                ('Image4', models.ImageField(blank=True, null=True, upload_to=core.models.carousel_image_handle)),
                ('Image5', models.ImageField(blank=True, null=True, upload_to=core.models.carousel_image_handle)),
            ],
        ),
    ]
