# Generated by Django 3.2.7 on 2022-06-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Carousel'},
        ),
    ]
