# Generated by Django 3.2.7 on 2022-06-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220626_1243'),
        ('core', '0003_alter_carousel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headings', models.ManyToManyField(to='products.Category')),
            ],
            options={
                'verbose_name': 'Featured Section',
            },
        ),
    ]
