# Generated by Django 4.0.3 on 2022-07-03 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220626_1243'),
        ('core', '0004_featuredsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandImage', models.ImageField(upload_to='brands')),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
            ],
            options={
                'verbose_name': 'Featured Brand',
            },
        ),
        migrations.CreateModel(
            name='FeaturedBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('BrandImage', models.ImageField(upload_to='brands')),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('Product1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products1', to='products.product')),
                ('Product2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products2', to='products.product')),
                ('Product3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products3', to='products.product')),
                ('Product4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products4', to='products.product')),
            ],
            options={
                'verbose_name': 'Featured Banner',
            },
        ),
    ]
