# Generated by Django 4.0.5 on 2022-07-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_featuredbrands_featuredbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupitem',
            name='Subgroup',
        ),
    ]
