# Generated by Django 4.0.5 on 2022-07-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
            ],
        ),
    ]
