# Generated by Django 3.2.7 on 2022-06-26 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(default='', max_length=10)),
            ],
            options={
                'verbose_name': 'Gender',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Size',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.gender')),
                ('ParentCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.CharField(blank=True, max_length=255)),
                ('Price', models.IntegerField()),
                ('Featured', models.BooleanField(default=False)),
                ('Latest', models.BooleanField(default=False)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='products')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='products')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='products')),
                ('Image4', models.ImageField(blank=True, null=True, upload_to='products')),
                ('Image5', models.ImageField(blank=True, null=True, upload_to='products')),
                ('Image6', models.ImageField(blank=True, null=True, upload_to='products')),
                ('Image7', models.ImageField(blank=True, null=True, upload_to='products')),
                ('Image8', models.ImageField(blank=True, null=True, upload_to='products')),
                ('Brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('Gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.gender')),
                ('Size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size')),
                ('Subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory')),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
    ]
