# Generated by Django 3.2.7 on 2022-06-26 12:43

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_handle),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_handle),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_handle),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image4',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_handle),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image5',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_handle),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image6',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_handle),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image7',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_handle),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image8',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_handle),
        ),
    ]
